const profileTypes = {
    
    UPDATE_PROFILE_REQUEST: 'UPDATE_PROFILE_REQUEST',
    UPDATE_PROFILE_FAILURE: 'UPDATE_PROFILE_FAILURE',

    UPDATE_ADDRESS_PROFILE: 'UPDATE_ADDRESS_PROFILE',
    UPDATE_PERSONAL_PROFILE: 'UPDATE_PERSONAL_PROFILE',
    CHANGE_EMAIL: 'CHANGE_EMAIL',
    CHANGE_PASSWORD: 'CHANGE_PASSWORD'
}

export default profileTypes