const utilTypes = {
    LOAD_TRANSACTIONS_REQUEST: 'LOAD_TRANSACTIONS_REQUEST',
    LOAD_TRANSACTIONS_SUCCESS: 'LOAD_TRANSACTIONS_SUCCESS',
    LOAD_TRANSACTIONS_FAILURE: 'LOAD_TRANSACTIONS_FAILURE',


}

export default utilTypes;