const utilTypes = {
    LOAD_TRANSACTIONS_REQUEST: 'LOAD_TRANSACTIONS_REQUEST',
    LOAD_TRANSACTIONS_SUCCESS: 'LOAD_TRANSACTIONS_SUCCESS',
    LOAD_TRANSACTIONS_FAILURE: 'LOAD_TRANSACTIONS_FAILURE',

    CURRENCY_EXCHANGE_REQUEST: 'CURRENCY_EXCHANGE_REQUEST',
    CURRENCY_EXCHANGE_SUCCESS: 'CURRENCY_EXCHANGE_SUCCESS',
    CURRENCY_EXCHANGE_FAILURE: 'CURRENCY_EXCHANGE_FAILURE',
}

export default utilTypes;