const utilTypes = {
    LOAD_TRANSACTIONS_REQUEST: 'LOAD_TRANSACTIONS_REQUEST',
    LOAD_TRANSACTIONS_SUCCESS: 'LOAD_TRANSACTIONS_SUCCESS',
    LOAD_TRANSACTIONS_FAILURE: 'LOAD_TRANSACTIONS_FAILURE',

    CURRENCY_EXCHANGE_REQUEST: 'CURRENCY_EXCHANGE_REQUEST',
    CURRENCY_EXCHANGE_SUCCESS: 'CURRENCY_EXCHANGE_SUCCESS',
    CURRENCY_EXCHANGE_FAILURE: 'CURRENCY_EXCHANGE_FAILURE',

    TOGGLE_SIDEBAR: 'TOGGLE_SIDEBAR',
    SET_ACTIVE_LINK: 'SET_ACTIVE_LINK'
}

export default utilTypes;