const investmentTypes = {
    GET_INVESTMENT_REQUEST: 'GET_INVESTMENT_REQUEST',
    GET_INVESTMENT_SUCCESS: 'GET_INVESTMENT_SUCCESS',
    GET_INVESTMENT_INFO: 'GET_INVESTMENT_INFO',
    GET_INVESTMENT_FAILURE: 'GET_INVESTMENT_FAILURE'
}

export default investmentTypes