const adminTypes = {
    LOADING_REQUEST: 'LOADING_REQUEST',
    MODAL_DATA_LOADING_REQUEST: 'MODAL_DATA_LOADING_REQUEST',
    ADMIN_ERROR: 'ADMIN_ERROR',

    GET_USERS: 'GET_USERS',
    GET_WITHDRAWALS: 'GET_WITHDRAWALS',
    GET_DEPOSITS: 'GET_DEPOSITS',

    UPDATE_TOPUP: 'UPDATE_TOPUP',
    ACTIVATE_PAYMENT: 'ACTIVATE_PAYMENT',
    TRANSACTION_SUCCESS: 'TRANSACTION_SUCCESS',
    UPDATE_PASSWORD: 'UPDATE_PASSWORD',
    TOGGLE_USER_STATUS: 'TOGGLE_USER_STATUS',
    RESET: 'RESET',
    DELETE_PAYMENT: 'DELETE_PAYMENT',
    CONFIRM_WITHDRAW: 'CONFIRM_WITHDRAW',
    DELETE_WITHDRAW: 'DELETE_WITHDRAW',
    ACCOUNT_SYNC: 'ACCOUNT_SYNC'
}

export default adminTypes;