const transactionTypes = {
    TRANSACTION_REQUEST: 'TRANSACTION_REQUEST',
    TRANSACTION_SUCCESS: 'TRANSACTION_SUCCESS',
    TRANSACTION_FAILURE: 'TRANSACTION_FAILURE'
}

export default transactionTypes