const transactionTypes = {
    TRANSACTION_REQUEST: 'TRANSACTION_REQUEST',
    TRANSACTION_SUCCESS: 'TRANSACTION_SUCCESS',
    GET_DEPOSIT_TRANSACTIONS: 'GET_DEPOSIT_TRANSACTIONS',
    GET_WITHDRAW_TRANSACTIONS: 'GET_WITHDRAW_TRANSACTIONS',
    GET_PENDING_TRANSACTIONS: 'GET_PENDING_TRANSACTIONS',
    TRANSACTION_FAILURE: 'TRANSACTION_FAILURE',

    SELECTED_TAB: 'SELECTED_TAB'
}

export default transactionTypes