const depositTypes = {
    NAV1_PAYMENT_METHOD: 'NAV1_PAYMENT_METHOD',
    NAV2_FUND_DEPOSIT: 'NAV2_FUND_DEPOSIT',
    NAV3_CONFIRM_DEPOSIT: 'NAV3_CONFIRM_DEPOSIT',
    NAV4_MAKE_DEPOSIT: 'NAV4_MAKE_DEPOSIT',

    CURRENCY_EXCHANGE_REQUEST: 'CURRENCY_EXCHANGE_REQUEST',
    CURRENCY_EXCHANGE_SUCCESS: 'CURRENCY_EXCHANGE_SUCCESS',
    CURRENCY_EXCHANGE_FAILURE: 'CURRENCY_EXCHANGE_FAILURE',
    
    UPDATE_WALLET_REQUEST: 'UPDATE_WALLET_REQUEST',
    UPDATE_WALLET_SUCCESS: 'UPDATE_WALLET_SUCCESS',
    UPDATE_WALLET_FAILURE: 'UPDATE_WALLET_FAILURE',
    
}

export default depositTypes