const planTypes = {
    PLAN_REQUEST: 'PLAN_REQUEST',
    PLAN_ERROR: 'PLAN_ERROR',
    PLANS: 'PLANS',
    CREATE_INVESTMENT_PLAN: 'CREATE_INVESTMENT_PLAN',
    SELECTED_PLAN: 'SELECTED_PLAN',

    NAVIGATE_TO_PLAN_CONTAINER: 'NAVIGATE_TO_PLAN_CONTAINER',
    NAVIGATE_TO_PLAN_INVESTMENT: 'NAVIGATE_TO_PLAN_INVESTMENT'
}

export default planTypes

