const planTypes = {
    PLAN_REQUEST: 'PLAN_REQUEST',
    PLAN_ERROR: 'PLAN_ERROR',
    PLANS: 'PLANS',
    CREATE_INVESTMENT_PLAN: 'CREATE_INVESTMENT_PLAN',
    CREATE_INVESTMENT_PLAN_ERROR: 'CREATE_INVESTMENT_PLAN_ERROR',
    SELECTED_PLAN: 'SELECTED_PLAN',

    NAVIGATE_TO_PLAN_CONTAINER: 'NAVIGATE_TO_PLAN_CONTAINER',
    NAVIGATE_TO_PLAN_INVESTMENT: 'NAVIGATE_TO_PLAN_INVESTMENT',
    
    SEND_ID_CODE_MAIL: 'SEND_ID_CODE_MAIL',
}

export default planTypes

