const withdrawTypes = {
    WITHDRAW_REQUEST: 'WITHDRAW_REQUEST',
    GET_WITHDRAW_REQUEST: 'GET_WITHDRAW_REQUEST',
    GET_WITHDRAW_ERROR: 'GET_WITHDRAW_ERROR',
    
    GET_WITHDRAW_ACCOUNTS: 'GET_WITHDRAW_ACCOUNTS',
    CREATE_WITHDRAW_ACCOUNT: 'CREATE_WITHDRAW_ACCOUNT',
    REQUEST_WITHDRAW_FUND: 'REQUEST_WITHDRAW_FUND',
    RESET_WITHDRAW: 'RESET_WITHDRAW',

    NAV1_WITHDRAW_METHOD: 'NAV1_WITHDRAW_METHOD',
    NAV2_WITHDRAW_FUND: 'NAV2_WITHDRAW_FUND',
    NAV3_WITHDRAW_CONFIRM: 'NAV3_WITHDRAW_CONFIRM'
}
export default withdrawTypes